// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6q12HulPS7kIvvhcmdlFw-frfv-ngyAk',
    appId: '1:478543893363:web:d1e5e76f851c8be3402b06',
    messagingSenderId: '478543893363',
    projectId: 'chatapp-6025a',
    authDomain: 'chatapp-6025a.firebaseapp.com',
    storageBucket: 'chatapp-6025a.firebasestorage.app',
    measurementId: 'G-63Y9RXP9EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbGTzZ1cu7oZUskUnv8n9O_u9iq4KI2c4',
    appId: '1:478543893363:android:1bbd091a9381c0be402b06',
    messagingSenderId: '478543893363',
    projectId: 'chatapp-6025a',
    storageBucket: 'chatapp-6025a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC12bMeClKxTX8msEhcbVavXt4eUFmuijA',
    appId: '1:478543893363:ios:755d7ff8fc914317402b06',
    messagingSenderId: '478543893363',
    projectId: 'chatapp-6025a',
    storageBucket: 'chatapp-6025a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6q12HulPS7kIvvhcmdlFw-frfv-ngyAk',
    appId: '1:478543893363:web:3f1463c322803c51402b06',
    messagingSenderId: '478543893363',
    projectId: 'chatapp-6025a',
    authDomain: 'chatapp-6025a.firebaseapp.com',
    storageBucket: 'chatapp-6025a.firebasestorage.app',
    measurementId: 'G-CRT0Z1271H',
  );
}
